openapi: 3.0.0
info:
  title: Time Complexity Tutor API
  version: 1.0.0
  description: API for interacting with the Time Complexity Tutor chatbot.

servers:
  - url: http://localhost:5001
    description: Local server

paths:
  /chat:
    post:
      summary: Send a message to the time complexity tutor
      description: This endpoint allows users to send a message to the tutor and optionally specify their learning stage.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The user's message to the tutor
                  example: "What is time complexity?"
                stage:
                  type: integer
                  description: Optional learning stage (1–4)
                  minimum: 1
                  maximum: 4
                  example: 2
              required:
                - message
      responses:
        '200':
          description: Successful response from the tutor
          content:
            application/json:
              schema:
                type: object
                properties:
                  reply:
                    type: string
                    description: The assistant's response
                    example: "Great question! Time complexity helps us understand how fast an algorithm runs."
        '400':
          description: Bad request. Missing message field.
        '500':
          description: Internal server error

components:
  schemas: {}
